#! /bin/bash

# Add directories to PATH.
# If the directory is in PATH already, it is moved to the front.

for pathdir in /opt/homebrew/bin; do
    # Exclude non-directories.
    test -d "$pathdir" || continue
    # Exclude non-canonical names.
    case $pathdir in
    */./*|*/../*)
        continue;;
    esac
    # Prepend to PATH, remove existing occurrences.
    PATH="$pathdir$(echo :$PATH: | sed "s%:$pathdir:%:%g;s%:$%%")"
done
