#! /bin/bash

# Add bin directories under ~/.opt to PATH

for opt_path in ~/.opt/*/bin; do
    case :$PATH: in
    *:$opt_path:*)
        # already in PATH
        ;;
    *)
        PATH="$opt_path:$PATH"
        ;;
    esac
done
