import = ["~/.config/alacritty/alacritty-common.toml"]

working_directory = 'C:/Users/Pavel'

[font]
size = 13.0

[shell]
program = "C:/Program Files/Git/bin/bash.exe"

[window]
startup_mode = "Maximized"
