[colors.bright]
black = "#5e5c64"
blue = "#2a7bde"
cyan = "#33c7de"
green = "#33d17a"
magenta = "#c061cb"
red = "#f66151"
white = "#ffffff"
yellow = "#e9ad0c"

[colors.cursor]
cursor = "#52ad70"
text = "#000000"

[colors.normal]
black = "#171421"
blue = "#12488b"
cyan = "#2aa1b3"
green = "#26a269"
magenta = "#a347ba"
red = "#c01c28"
white = "#d0cfcc"
yellow = "#a2734c"

[colors.primary]
background = "#000000"
foreground = "#d0cfcc"

[font]
normal.family = "JetBrains Mono"

[window]
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "N"
mods = "Super"
mode = "~Vi"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "V"
mods = "Super"
mode = "~Vi"
action = "Paste"

[debug]
log_level = "Warn"
persistent_logging = false
