[font]
normal.family = "JetBrains Mono"

[window]
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "N"
mods = "Super"
mode = "~Vi"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "V"
mods = "Super"
mode = "~Vi"
action = "Paste"

[[mouse.bindings]]
mouse = "Middle"
mode = "~Vi"
action = "None"

[[mouse.bindings]]
mouse = "Middle"
mods = "Shift"
mode = "~Vi"
action = "Paste"

[debug]
log_level = "Warn"
persistent_logging = false
