import = ["~/.config/alacritty/alacritty-common.toml"]

[font]
size = 15.0

[shell]
program = "/usr/bin/tmux"

[env]
prompt_color_force = "1"

[window]
startup_mode = "Windowed"
dimensions.columns = 120
dimensions.lines = 36
